# ==================================================
# FILE: .github/workflows/auto-approve.yml
# Automatically approve all PRs (use with caution!)
# ==================================================
name: Auto Approve PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-approve:
    name: Auto Approve
    runs-on: ubuntu-latest
    
    steps:
      - name: Auto approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ **Auto-approved** for team collaboration!\n\nRemember to review code manually before merging. 🚀'
            })

# ⚠️ WARNING: This auto-approves ALL pull requests!
# Only use this for small student teams during development.
# Remove this workflow for production projects!